### ISSUE TITLE
How can I train my own model?

### ISSUE THREAD

**Issue by czy-0326** [dongfang-steven-yang/faraway-frustum#2]
In readme, I donot find anything about training this model,can you tell me if I can train my own model by this code?

**Comment by dongfang-steven-yang** [comment]
Hi, currently we only released the pre-trained model. We will add the code of the prediction model soon. The model is not complex, you can refer to our arXiv paper first and check back again. 

Thanks,
DF

**Comment by czy-0326** [comment]
@dongfang-steven-yang  Thank you for your reply.

**Comment by Ekim-Yurtsever** [comment]
Please see the training scripts in \faraway-frustum-net
