### ISSUE TITLE
How to read the code of test model？

### ISSUE THREAD

**Issue by BoXingJinQiu** [dongfang-steven-yang/faraway-frustum#3]
Hello, @dongfang-steven-yang , Can you tell me how can I read the code of the predict model?  I cannot see the code of  the pre-trained model, and I want to learn the code of the faraway frustum net.

**Comment by dongfang-steven-yang** [comment]
Hi, currently we only released the pre-trained model. We will add the code of the prediction model soon. The model is not complex, you can refer to our arXiv paper first and check back again. 

Thanks,
DF

**Comment by Ekim-Yurtsever** [comment]
Please check faraway-frustum-net/models/models.py
