### ISSUE TITLE
What's the function of so many split folder?

### ISSUE THREAD

**Issue by czy-0326** [dongfang-steven-yang/faraway-frustum#4]
!
![sendpix1](https://user-images.githubusercontent.com/74098358/104413365-2f84d300-55a9-11eb-9292-984c9397ffbc.jpg)
[sendpix0](https://user-images.githubusercontent.com/74098358/104413354-298ef200-55a9-11eb-83b8-c5ecaa18e7ac.jpg)
As it can be seen in the picture ,there are a lot of split  ,which split I should use to train  my car model and pedestrian model.In your paper , you write that 
![sendpix2](https://user-images.githubusercontent.com/74098358/104413745-d8cbc900-55a9-11eb-8685-75a19655e101.jpg)

**Comment by dongfang-steven-yang** [comment]
Hi, 

The data we used to train the network is generated by the script of  `data/frustum_data/create_frustum_data.py`. That is to say, as shown in the code, we use the `split01`. You can refer to the python script. 

Just ignore other splits. They were just used for preliminary experiments. 

If a split is appended with a number, for example, `train_car_60`, it means the training split that contains cars of more than 60 meters. However, these appended txts are only used to calculate the scores, not used in training the model. 

Sorry about the mess in the repo. We may update it in the future. 

--DF

**Comment by czy-0326** [comment]
@dongfang-steven-yang  Thankyou for your reply .By reading the code this afternoon,  I have kown that .But  I think that this code still has some problems.The script of  'data/frustum_data/create_frustum_data.py ' is uesd to generate frustums for ped , and  I modify the this script to generate frustums  for car.  And  I will use the frustums data for ped and car to train the model for ped and car respectively. If your two pre-trained models (which are uploaded in google ) for ped and car are the same?

**Comment by dongfang-steven-yang** [comment]
Yes, so in the python script of `create_frustum_data.py`, you need to switch between car and ped (there is a variable called `category` in the script) to generate the data for both.

**Comment by czy-0326** [comment]
@dongfang-steven-yang  Sorry, I have the new problems,when I calculate the mAP for faraway objects according to 
![sendpix1](https://user-images.githubusercontent.com/74098358/104556404-83132180-567a-11eb-9de1-118fe4d6ef9d.jpg)
I come across new problem 
![sendpix2](https://user-images.githubusercontent.com/74098358/104556502-ac33b200-567a-11eb-8b75-32036f7926e7.jpg)
